### ISSUE TITLE
Error having to do with newlines in CSVs

### ISSUE THREAD

**Issue by smcoll** [burke-software/django-simple-import#39]
```
Error at /simple_import/match_columns/3/
new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
```

django==1.6.8
django-simple-import==1.19

PR incoming... first i'm gonna see if i can isolate the offending newline and make a test, if it doesn't take too long.

**Comment by bufke** [comment]
Closing this due to age - more tests always welcome.
