### ISSUE TITLE
Any plan for supporting .sql import?

### ISSUE THREAD

**Issue by sunjoomoon** [burke-software/django-simple-import#45]
Anytime soon to support sql import? Will be cool to support sql.

**Comment by bufke** [comment]
What would be the use case here? This project is for letting end users import data and matches columns to database fields. 

sql would run on the database itself. Reopen if you'd like to make a case for this but I don't see how it's related.

**Comment by sunjoomoon** [comment]
Sorry for the long vacancy. Quite often site migration involves sql file, and for less experienced web based solution (like yours) makes cool sense. Just a thought. Not all are comfortable with shell command. Btw, yours just rock. Thanks again.
