### ISSUE TITLE
migration broken for Django 1.7

### ISSUE THREAD

**Issue by smcoll** [burke-software/django-simple-import#47]
`KeyError: u"Migration simple_import.0001_initial dependencies reference nonexistent parent node (u'contenttypes', u'0002_remove_content_type_name')"`

Migration "0002_remove_content_type_name" wasn't introduced until Django 1.8, so i believe the fix will be to depend on "0001_initial" instead.

Using Django 1.7.8.

**Comment by bufke** [comment]
Forgot to close this, which was fixed some time ago.
